[project]
name = "simple"
r_version = "4.5"
repositories = [
    {alias = "posit", url = "https://packagemanager.posit.co/cran/2025-05-12/"}
]
dependencies = [
    {name = "Rcpp", force_source = true},
]

[project.packages_env_vars.Rcpp]
PKG_CXXFLAGS = '-v'
